version: "3.7"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - type: volume
        source: minio-buckets
        target: /test-data
    networks:
      ecs_emulation:
        ipv4_address: '169.254.170.3'
    depends_on:
      - minio

  minio:
    build:
      context: .
      dockerfile: Dockerfile-minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO_REGION=us-east-1
    ports:
      - "9000:9000"
    volumes:
      - type: volume
        source: minio-buckets
        target: /test-data
    networks:
      ecs_emulation:
        ipv4_address: '169.254.170.4'

volumes:
  minio-buckets:

networks:
  ecs_emulation:
    driver: bridge
    ipam:
      config:
        - subnet: '169.254.170.0/24'
