version: 2
jobs:
  build:
    # To allow volume mount to extract coverage
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install code coverage reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            set -x
            docker-compose build
            ./cc-test-reporter before-build
            touch coverage.xml
            docker-compose run --rm --volume=${PWD}/coverage.xml:/coverage.xml test sh test_with_coverage.sh
            # Suspect that combining coverage reports converts to absolute paths, which are not found in host
            sed -i 's/filename="\//filename="/g' coverage.xml
            ./cc-test-reporter after-build --exit-code $?
